Repository modflowpy/flopy, pull requests merged in 2024-06, with the labels that each got.

#2217 chore(deps): require jupyter_client>=8.4.0 for now
  etc/environment.yml
  pyproject.toml
Labels: dependencies, documentation

#2239 test: replace test_mf6_examples.py with CI test job
  .github/workflows/commit.yml
  .github/workflows/mf6.yml
  .github/workflows/regression.yml
  autotest/regression/conftest.py
  autotest/regression/test_mf6_examples.py
Labels: modflow 6, maintenance

#2238 refactor: np.where(cond) -> np.asarray(cond).nonzero()
  autotest/conftest.py
  autotest/test_lake_connections.py
  autotest/test_mt3d.py
  autotest/test_sfr.py
  autotest/test_zonbud_utility.py
  flopy/discretization/grid.py
  flopy/discretization/structuredgrid.py
  flopy/export/netcdf.py
  flopy/export/utils.py
  flopy/export/vtk.py
  flopy/mf6/utils/lakpak_utils.py
  flopy/mf6/utils/model_splitter.py
  flopy/modflow/mfrch.py
  flopy/modflow/mfsfr2.py
  flopy/pest/params.py
  flopy/plot/plotutil.py
  flopy/utils/binaryfile.py
  flopy/utils/check.py
  flopy/utils/compare.py
  flopy/utils/cvfdutil.py
  flopy/utils/datafile.py
  flopy/utils/flopy_io.py
  flopy/utils/formattedfile.py
  flopy/utils/geometry.py
  flopy/utils/gridgen.py
  flopy/utils/lgrutil.py
  flopy/utils/observationfile.py
  flopy/utils/particletrackfile.py
  flopy/utils/rasters.py
  flopy/utils/sfroutputfile.py
  flopy/utils/swroutputfile.py
  flopy/utils/triangle.py
  flopy/utils/util_list.py
  flopy/utils/voronoi.py
  flopy/utils/zonbud.py
Labels: bug, maintenance

#2242 fix(PlotMapView): default to all layers in plot_pathline()
  flopy/plot/map.py
Labels: bug

#2240 chore: remove code.json and disclaimer, update scripts
  DISCLAIMER.md
  README.md
  code.json
  docs/PyPI_release.md
  flopy/DISCLAIMER.md
  scripts/README.md
  scripts/update_version.py
Labels: maintenance

#2225 refactor(get-modflow): support ARM macs by default (previously opt-in)
  autotest/test_get_modflow.py
  flopy/utils/get_modflow.py
Labels: enhancement

#2235 fix(Raster): reclassify np.float64 correctly
  flopy/utils/rasters.py
Labels: bug
