Repository modflowpy/flopy, pull requests merged in 2025-01, with the labels that each got.

#2409 test: mark tests requiring optional dependencies
  autotest/test_mf6.py
  autotest/test_model_splitter.py
  autotest/test_plot_cross_section.py
  autotest/test_plot_map_view.py
Labels: maintenance

#2404 feat(mf2005,mf2k): allow loading custom flopy packages
  autotest/test_modflow.py
  flopy/modflow/mf.py
Labels: enhancement

#2414 chore(dependencies): update conda environment
  .docs/Notebooks/array_output_tutorial.py
  .docs/Notebooks/mt3dms_sft_lkt_uzt_tutorial.py
  .docs/Notebooks/plot_cross_section_example.py
  .docs/Notebooks/plot_map_view_example.py
  .docs/Notebooks/seawat_henry_example.py
  .docs/Notebooks/shapefile_feature_examples.py
  autotest/conftest.py
  autotest/test_notebooks.py
  etc/environment.yml
Labels: bug, dependencies, maintenance

#2421 refactor(FlopyBinaryData): use properties, deprecate set_float
  flopy/mf6/utils/binarygrid_util.py
  flopy/utils/observationfile.py
  flopy/utils/swroutputfile.py
  flopy/utils/utils_def.py
Labels: deprecation, maintenance
